# Use an official Python base image
FROM python:3.13.9-slim


# Set working directory
WORKDIR /GamesHub

RUN echo "hosts: files dns" > /etc/nsswitch.conf


# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .



# Expose port
EXPOSE 8000

# Start Gunicorn
CMD gunicorn GamesHub.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --threads 2 --preload


