# Generated by Django 5.2.3 on 2025-12-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Open'), (2, 'Pending'), (3, 'Closed'), (4, 'Resolved')], default=0, null=True),
        ),
    ]
