# Generated by Django 5.2.3 on 2025-12-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0002_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Open'), (2, 'Pending'), (3, 'Closed'), (4, 'Resolved')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Refund'), (2, 'Executable_Issue'), (3, 'Other')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Open'), (2, 'Pending'), (3, 'Closed'), (4, 'Resolved')], default=1, null=True),
        ),
    ]
