# Generated by Django 5.2.3 on 2025-12-12 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0004_report_assigned_staff_report_resolution_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_comment',
            field=models.TextField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='admin_comment',
            field=models.TextField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_staff_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_staff_ticket', to=settings.AUTH_USER_MODEL),
        ),
    ]
