# Generated by Django 5.2.3 on 2025-12-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0007_alter_banuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banuser',
            name='baned_date',
            field=models.DateField(),
        ),
    ]
