# Generated by Django 5.2.3 on 2025-10-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=256)),
                ('passWord', models.CharField(max_length=256)),
                ('profilePicture', models.FileField(blank=True, null=True, upload_to='Media/ProfilePicture/')),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField()),
                ('userType', models.IntegerField(default=0)),
            ],
        ),
    ]
