# Generated by Django 5.2.3 on 2025-10-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='time',
            field=models.IntegerField(default=1761227944.0939343),
        ),
    ]
