# Generated by Django 5.2.3 on 2025-10-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='FirstName', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='LastName', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=128),
        ),
    ]
