# Generated by Django 5.2.3 on 2025-10-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_appuser_is_active_alter_otp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='time',
            field=models.IntegerField(default=1760888507.062502),
        ),
    ]
