# Generated by Django 5.2.3 on 2025-10-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_otp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='time',
            field=models.IntegerField(),
        ),
    ]
