# Generated by Django 5.2.3 on 2025-10-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_alter_otp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profilePicture',
            field=models.FileField(blank=True, null=True, upload_to='ProfilePicture/'),
        ),
    ]
