# Generated by Django 5.2.3 on 2025-10-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_alter_otp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='time',
            field=models.IntegerField(default=1760890668.8174198),
        ),
    ]
