# Generated by Django 5.2.3 on 2025-10-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_user_id_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('account', models.EmailField(max_length=254)),
                ('time', models.IntegerField(verbose_name=1760206671.4326963)),
            ],
        ),
    ]
