# Generated by Django 5.2.3 on 2025-10-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='time',
            field=models.IntegerField(default=1760206834.1317399),
        ),
    ]
