# Generated by Django 5.2.3 on 2025-10-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_alter_appuser_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profilePicture',
            field=models.CharField(null=True),
        ),
    ]
