# Generated by Django 5.2.3 on 2025-10-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_alter_otp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='account',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='time',
            field=models.IntegerField(default=1760207106.2197073),
        ),
    ]
