# Generated by Django 5.2.3 on 2025-10-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_alter_appuser_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phoneNumber',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='profilePicture',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
