# Generated by Django 5.2.3 on 2025-10-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_alter_appuser_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phoneNumber',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
