# Generated by Django 5.2.3 on 2025-11-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_alter_appuser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profilePicture',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
