# Generated by Django 5.2.3 on 2025-11-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_alter_appuser_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phoneNumber',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
