# Generated by Django 5.2.3 on 2025-11-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_alter_appuser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='time',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
