# Generated by Django 5.2.3 on 2025-11-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0012_alter_otp_otp_alter_otp_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='valid_email',
            field=models.BooleanField(default=False),
        ),
    ]
