# Generated by Django 5.2.3 on 2025-11-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constants',
            name='value',
            field=models.CharField(max_length=64),
        ),
    ]
