# Generated by Django 5.2.3 on 2025-11-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedaccesstoken',
            name='blacklisted_time',
            field=models.DateTimeField(),
        ),
    ]
