# Generated by Django 5.2.3 on 2025-11-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utills', '0003_blacklistedaccesstoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklistedaccesstoken',
            old_name='blaclisted_time',
            new_name='blacklisted_time',
        ),
    ]
