# Generated by Django 5.2.3 on 2025-12-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utills', '0003_upvotedownvotecontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotedownvotecontrol',
            name='upvotedownvote',
            field=models.BooleanField(default=None),
        ),
    ]
