# Generated by Django 5.2.3 on 2025-12-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utills', '0004_alter_upvotedownvotecontrol_upvotedownvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotedownvotecontrol',
            name='upvotedownvote',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
