# Generated by Django 5.2.3 on 2025-10-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('publishedDate', models.DateField()),
                ('description', models.CharField(max_length=4096)),
                ('price', models.FloatField(default=0)),
                ('developer', models.CharField(max_length=256)),
                ('platforms', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=256)),
            ],
        ),
    ]
