# Generated by Django 5.2.3 on 2025-10-23 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('publishedDate', models.DateField()),
                ('description', models.CharField(max_length=4096)),
                ('price', models.FloatField(default=0)),
                ('developer', models.CharField(max_length=256)),
                ('platforms', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('games', models.ManyToManyField(to='Store.game')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('games', models.ManyToManyField(to='Store.game')),
            ],
        ),
    ]
