# Generated by Django 5.2.3 on 2025-10-19 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_alter_otp_time'),
        ('Store', '0002_rename_games_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.game')),
            ],
        ),
    ]
