# Generated by Django 5.2.3 on 2025-10-28 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_game_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
