# Generated by Django 5.2.3 on 2025-10-19 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='cart',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.cart'),
        ),
    ]
