# Generated by Django 5.2.3 on 2025-11-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_game_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='no_of_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
