# Generated by Django 5.2.3 on 2025-11-12 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_game_no_of_rating_game_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_picture',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='GamesMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, ''), (1, 'Cover'), (2, 'Screen_Shot'), (3, 'Trailer')], default=0, null=True)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.game')),
            ],
        ),
    ]
