# Generated by Django 5.2.3 on 2025-10-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_remove_game_cart_cart_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='games',
        ),
        migrations.AddField(
            model_name='cart',
            name='games',
            field=models.ManyToManyField(to='Store.game'),
        ),
    ]
