# Generated by Django 5.2.3 on 2025-11-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_game_cover_picture_gamesmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesmedia',
            name='media_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, ''), (1, 'Screen_Shot'), (2, 'Trailer')], default=0, null=True),
        ),
    ]
