# Generated by Django 5.2.3 on 2025-11-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_gamesmedia_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesmedia',
            name='media_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Screen_Shot'), (2, 'Trailer')], default=0, null=True),
        ),
    ]
