# Generated by Django 5.2.3 on 2025-10-22 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_alter_otp_time'),
        ('Store', '0006_remove_cart_games_cart_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('games', models.ManyToManyField(to='Store.game')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('games', models.ManyToManyField(to='Store.game')),
            ],
        ),
    ]
