# Generated by Django 5.2.3 on 2025-12-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_remove_wallettransaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='id',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
