# Generated by Django 5.2.3 on 2025-12-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_remove_wallettransaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_name', models.CharField(max_length=32)),
                ('sale_end_date', models.DateField()),
                ('games', models.ManyToManyField(to='Store.game')),
            ],
        ),
    ]
