# Generated by Django 5.2.3 on 2025-12-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
