# Generated by Django 5.2.3 on 2025-12-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_sale_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cover_picture',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
