# Generated by Django 5.2.3 on 2025-12-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_sale_cover_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['id']},
        ),
    ]
