# Generated by Django 5.2.3 on 2025-12-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_alter_game_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
