# Generated by Django 5.2.3 on 2025-12-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_alter_sale_sale_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
