# Generated by Django 5.2.3 on 2025-12-14 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_alter_sale_sale_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.wallet'),
        ),
    ]
