# Generated by Django 5.2.3 on 2025-10-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesBuzz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinteraction',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '.....'), (1, '*....'), (2, '**...'), (3, '***..'), (4, '****.'), (5, '*****')], default=0, null=True),
        ),
    ]
