# Generated by Django 5.2.3 on 2025-11-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesBuzz', '0002_alter_gameinteraction_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinteraction',
            name='in_library',
            field=models.BooleanField(default=True),
        ),
    ]
