# Generated by Django 5.2.3 on 2025-11-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesBuzz', '0003_gameinteraction_in_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinteraction',
            name='transaction_id',
            field=models.IntegerField(default=0),
        ),
    ]
