# Generated by Django 5.2.3 on 2025-12-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesBuzz', '0004_gameinteraction_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinteraction',
            name='id',
        ),
        migrations.AlterField(
            model_name='gameinteraction',
            name='transaction_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
