# Generated by Django 5.2.3 on 2025-12-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesBuzz', '0005_remove_gameinteraction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinteraction',
            name='transaction_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
