# Generated by Django 5.2.3 on 2025-12-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesBuzz', '0006_alter_gameinteraction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinteraction',
            name='downvote',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='gameinteraction',
            name='upvote',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
