# Generated by Django 5.2.3 on 2025-12-06 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesBuzz', '0007_gameinteraction_downvote_gameinteraction_upvote'),
        ('Store', '0016_alter_sale_sale_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinteraction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='gameinteraction',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='gameinteraction',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='gameinteraction',
            name='upvote',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(0, '.....'), (1, '*....'), (2, '**...'), (3, '***..'), (4, '****.'), (5, '*****')], default=0, null=True)),
                ('upvote', models.PositiveBigIntegerField(default=0, editable=False)),
                ('downvote', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
