# Generated by Django 5.2.3 on 2025-12-06 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesBuzz', '0008_remove_gameinteraction_comment_and_more'),
        ('Store', '0016_alter_sale_sale_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, '.....'), (1, '*....'), (2, '**...'), (3, '***..'), (4, '****.'), (5, '*****')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'game')},
        ),
    ]
