# Generated by Django 5.2.3 on 2025-12-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesBuzz', '0009_alter_review_rating_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, '.....'), (1, '*....'), (2, '**...'), (3, '***..'), (4, '****.'), (5, '*****')]),
        ),
    ]
