# Generated by Django 5.2.3 on 2025-12-19 08:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamesBuzz', '0010_alter_review_rating'),
        ('Store', '0017_alter_wallettransaction_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameinteraction',
            unique_together={('user', 'game', 'in_library')},
        ),
    ]
