# Generated by Django 5.2.3 on 2025-12-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvote',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvote',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='downvote',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='upvote',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
