# Generated by Django 5.2.3 on 2025-12-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0003_comment_downvote_comment_upvote_post_downvote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='downvote',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upvote',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='downvote',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvote',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
