# Generated by Django 5.2.3 on 2025-12-05 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0004_alter_comment_downvote_alter_comment_upvote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Screen_Shot'), (2, 'Gameplay')], default=0, null=True)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.post')),
            ],
        ),
    ]
