# Generated by Django 5.2.3 on 2025-12-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0005_postmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=4096),
        ),
    ]
