# Generated by Django 5.2.3 on 2025-12-08 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0006_alter_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmedia',
            name='media_type',
        ),
    ]
